# Generated by Django 6.0.4 on 2026-04-19 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (Arabic)')),
                ('image', models.ImageField(upload_to='categories/')),
                ('custom_fields_template', models.JSONField(blank=True, default=list, help_text='Enter a list of field names. e.g., ["Color", "Size"]')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='e.g., DOZEN, PCS, CARTON', max_length=50)),
                ('name_ar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='e.g., Milliliter, Liter, Kg', max_length=50)),
                ('name_ar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Product Name (English)')),
                ('name_ar', models.CharField(max_length=200, verbose_name='Product Name (Arabic)')),
                ('image_1', models.ImageField(upload_to='products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('dynamic_attributes', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
                ('available_units', models.ManyToManyField(blank=True, to='store.unit')),
                ('available_volumes', models.ManyToManyField(blank=True, to='store.volume')),
            ],
        ),
    ]
