# Generated by Django 6.0.4 on 2026-04-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='custom_fields_template',
            field=models.JSONField(blank=True, default=list, help_text='Enter a list of field names. e.g., ["Color", "Size"]', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dynamic_attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
