# Generated by Django 6.0.4 on 2026-04-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_custom_fields_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_text_en', models.CharField(help_text='e.g. Grow Green Trading Co.', max_length=100)),
                ('small_text_ar', models.CharField(help_text='e.g. شركة جرو جرين', max_length=100)),
                ('main_text_white_en', models.CharField(help_text='e.g. Luxury', max_length=100)),
                ('main_text_white_ar', models.CharField(help_text='e.g. تصميم', max_length=100)),
                ('main_text_gold_en', models.CharField(help_text='e.g. Design', max_length=100)),
                ('main_text_gold_ar', models.CharField(help_text='e.g. فاخر', max_length=100)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('button_text_en', models.CharField(default='Shop Now', max_length=50)),
                ('button_text_ar', models.CharField(default='تسوق الآن', max_length=50)),
            ],
        ),
    ]
